config/routes.rb
Rails.application.routes.draw do
  resources :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    validates :price, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    item = Item.create(item_params)

    redirect_to items_path
  end

  def edit
    @item = Item.find(params[:id])
  end

  def show
    @item = Item.find(params[:id])
    # rescue ActiveRecord::RecordNotFound => e
    # render 'missing_item'
  end

  def update
    @item = Item.find(params[:id])
    if @item
      @item.update(item_params)
    end
    redirect_to items_path
  end

  def destroy
    # Note that if the user has JavaScript disabled, the request will fall back to using GET.
    @item = Item.find(params[:id])
    if @item
      @item.destroy!
    end
    redirect_to items_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<h1> Items </h1>
<%= form_with model: @item do |form| %>
    <%= form.text_field :name, placeholder: "namaku bento" %>
    <%= form.text_field :price, placeholder: "price" %>
    <%= form.submit %>
  <% end %>

app/views/items/index.html.erb
<h1> Items </h1>
<table>
  <thead>
    <tr>
        <td><b>Name</b></td>
        <td><b>Price</b></td>
        <td></td>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.price %></td>
        <td>
          <table>
            <tbody>
              <tr>
                  <td><%= link_to "Show", item_path(item) %></td>
                  <td><%= link_to "Edit", edit_item_path(item) %></td>
                  <td><span><%= button_to "delete", item_path(item), :method => "delete" %></span></td>
              </tr>
            </tbody>
          </table>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<a href="/items/new">New Item</a>

app/views/items/missing_item.html.erb
<h1> Missing item </h1>

app/views/items/new.html.erb
<h3>Create an Item</h3>
<%= form_with model: @item do |form| %>
  <%= form.text_field :name, placeholder: "namaku bento" %>
  <%= form.text_field :price, placeholder: "price" %>
  <%= form.submit %>
<% end %>

app/views/items/show.html.erb
<h1> Items </h1>
<table>
  <thead>
    <tr>
        <td><b>Name</b></td>
        <td><b>Price</b></td>
        <td></td>
    </tr>
  </thead>
  <tbody>
    <tr>
        <td><%= @item.name %></td>
        <td><%= @item.price %></td>
        <td>
          <table>
            <tbody>
              <tr>
                  <td><%= link_to "Edit", edit_item_path(@item) %></td>
                  <td><span><%= button_to "delete", item_path(@item), :method => "delete" %></span></td>
              </tr>
            </tbody>
          </table>
        </td>
    </tr>
  </tbody>
</table>
<%= link_to "Back", items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>M4</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>